version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 8000:8000
      - 9443:9443

volumes:
  portainer-data: